version: "3.9"

services:
  laravelapp:
    container_name: laravelapp
    image: francescoxx/laravelapp:1.0.3
    mem_limit: 2g
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - "8100:8000"
    env_file:
      - .env
    depends_on:
      - db
  
  db:
    container_name: db
    image: postgres:12
    ports:
      - "8101:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}