FROM php:latest

RUN apt-get update && apt-get install -y \
    libpq-dev \
    curl

RUN docker-php-ext-install pdo pdo_pgsql

WORKDIR /var/www/html

COPY . .

RUN chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache

CMD php artisan serve --host=0.0.0.0 --port=8000

# docker build -t my-php-app .
# docker run -p 8100:8000 my-php-app
# docker run -d -p 8100:8000 --name laravelapp francescoxx/laravelapp:1.0.3
# docker-compose exec -T laravelapp php artisan migrate
# docker-compose exec db bash
